(function(){
const URL='https://hsrznmfeqajffrleeyly.supabase.co';
const KEY='sb_publishable_lQBoAETsI3XjQV21G4mpIQ_2xBzbsBT';
const AUTH='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzcnpubWZlcWFqZmZybGVleWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4OTc3MzcsImV4cCI6MjEwNDQ3MzczN30.sW3f1zi83QOJ9xlDIy6bbVNhDtcv8KtkrtDrNV5Ajvc';
async function req(path,options={}){const method=String(options.method||'GET').toUpperCase();const headers={apikey:KEY,Authorization:'Bearer '+AUTH,'Content-Type':'application/json',Prefer:'return=minimal',...(options.headers||{})};if(method==='GET'){headers['Cache-Control']='no-cache, no-store, max-age=0';headers.Pragma='no-cache'}const r=await fetch(URL+'/rest/v1/'+path,{...options,method,headers,cache:method==='GET'?'no-store':(options.cache||'default')});if(!r.ok){const detail=(await r.text()).slice(0,300);throw new Error('Supabase '+r.status+' ('+path+'): '+detail)}return r.status===204?null:r.json().catch(()=>null)}
function parse(raw){const out=[];for(const part of (raw||'').split(';')){const [a,values]=part.split(':');if(!a||!values)continue;for(const token of values.split(',')){const m=token.match(/^(\d+)(?:-(\d+))?$/);if(!m)continue;for(let p=+m[1];p<=+(m[2]||m[1]);p++)out.push({warehouse:'',aisle:+a,position:p,occupied:false})}}return out}
async function allFree(){let out=[],offset=0;while(true){const part=await req('qr_free_positions?select=warehouse,aisle,position,occupied&occupied=eq.false&order=warehouse,aisle,position&limit=1000&offset='+offset);out=out.concat(part||[]);if(!part||part.length<1000)break;offset+=1000}return out}
async function allRows(){const r=await req('qr_free_positions?select=warehouse,aisle,position,occupied&limit=1');return r||[]}
async function seed(){if((await allRows()).length)return;const rows=[];for(const d of ['DC2','DC3'])for(const x of parse(window.QR_FREE_RAW[d])){x.warehouse=d;rows.push(x)}for(let i=0;i<rows.length;i+=300){await req('qr_free_positions?on_conflict=warehouse,aisle,position',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(rows.slice(i,i+300))})}}
async function init(){return allFree()}
async function markOccupied(warehouse,aisle,position){await req('qr_free_positions?warehouse=eq.'+encodeURIComponent(warehouse)+'&aisle=eq.'+aisle+'&position=eq.'+position,{method:'PATCH',body:JSON.stringify({occupied:true,updated_at:new Date().toISOString()})});return true}
async function allOccupied(){let out=[],offset=0;while(true){const part=await req('qr_free_positions?select=warehouse,aisle,position,occupied,updated_at&occupied=eq.true&order=warehouse,aisle,position&limit=1000&offset='+offset);out=out.concat(part||[]);if(!part||part.length<1000)break;offset+=1000}return out}
async function refresh(){return allFree()}
function workerId(){let id=localStorage.getItem('qr-working-worker-id');if(!id){id='w-'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));localStorage.setItem('qr-working-worker-id',id)}return id}
function readJSON(key,fallback){try{const x=JSON.parse(localStorage.getItem(key)||'null');return x==null?fallback:x}catch(e){return fallback}}
function pendingWork(){return readJSON('qr-working-pending-v1',[])}
function savePendingWork(rows){localStorage.setItem('qr-working-pending-v1',JSON.stringify(rows))}
function saveWorkingCache(rows){try{localStorage.setItem('qr-working-cache-v1',JSON.stringify(rows||[]))}catch(e){}}
let workingSyncPromise=null,workingStateVersion=0;
function aisleKey(x){return String(x.warehouse)+'|'+Number(x.aisle)}
function sameOp(a,b){return aisleKey(a)===aisleKey(b)&&a.action===b.action&&a.op_id===b.op_id}
function applyWorkingOps(rows,ops){const out=(rows||[]).map(x=>({...x}));for(const op of ops){const key=aisleKey(op),i=out.findIndex(x=>aisleKey(x)===key);if(op.action==='remove'){if(i>=0)out.splice(i,1)}else if(op.action==='add'){const v={warehouse:op.warehouse,aisle:Number(op.aisle),worker_id:op.worker_id,updated_at:op.updated_at||new Date().toISOString()};if(i>=0)out[i]=v;else out.push(v)}}return out}
function queueWorkingOp(op){savePendingWork(pendingWork().filter(x=>aisleKey(x)!==aisleKey(op)).concat(op));saveWorkingCache(applyWorkingOps(readJSON('qr-working-cache-v1',[]),[op]));workingStateVersion++}
function removeQueuedOp(op){savePendingWork(pendingWork().filter(x=>!sameOp(x,op)));workingStateVersion++}
async function syncPendingWork(){if(typeof navigator!=='undefined'&&navigator.onLine===false)return;if(workingSyncPromise)return workingSyncPromise;workingSyncPromise=(async()=>{let pass=0;while(pass++<30&&!(typeof navigator!=='undefined'&&navigator.onLine===false)){const ops=pendingWork();if(!ops.length)break;let failed=false;for(const op of ops){const key=aisleKey(op),now=pendingWork().find(x=>aisleKey(x)===key);if(!now||!sameOp(now,op))continue;try{if(op.action==='add'){await req('qr_working_aisles?on_conflict=warehouse,aisle',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({warehouse:op.warehouse,aisle:Number(op.aisle),worker_id:op.worker_id,updated_at:op.updated_at})});const verify=await req('qr_working_aisles?select=warehouse,aisle,worker_id&warehouse=eq.'+encodeURIComponent(op.warehouse)+'&aisle=eq.'+Number(op.aisle));const row=(verify||[]).find(x=>aisleKey(x)===key),cur=pendingWork().find(x=>aisleKey(x)===key);if(!cur||!sameOp(cur,op))continue;if(!row||row.worker_id!==op.worker_id)throw new Error('Server nepotvrdil označení')}else if(op.action==='remove'){await req('qr_working_aisles?warehouse=eq.'+encodeURIComponent(op.warehouse)+'&aisle=eq.'+Number(op.aisle),{method:'DELETE'});const verify=await req('qr_working_aisles?select=warehouse,aisle,worker_id&warehouse=eq.'+encodeURIComponent(op.warehouse)+'&aisle=eq.'+Number(op.aisle));const cur=pendingWork().find(x=>aisleKey(x)===key);if(!cur||!sameOp(cur,op))continue;if((verify||[]).some(x=>aisleKey(x)===key))throw new Error('Server nepotvrdil zrušení')}removeQueuedOp(op);saveWorkingCache(applyWorkingOps(readJSON('qr-working-cache-v1',[]),[op]))}catch(e){const cur=pendingWork().find(x=>aisleKey(x)===key);if(cur&&sameOp(cur,op))failed=true}}if(failed)break}})();try{await workingSyncPromise}finally{workingSyncPromise=null}}
async function getWorkingAisles(){await syncPendingWork();const version=workingStateVersion;let rows=readJSON('qr-working-cache-v1',[]);if(!(typeof navigator!=='undefined'&&navigator.onLine===false)){try{const fresh=await req('qr_working_aisles?select=warehouse,aisle,worker_id,updated_at&order=warehouse,aisle');if(version===workingStateVersion){rows=fresh||[];saveWorkingCache(rows)}else rows=readJSON('qr-working-cache-v1',rows)}catch(e){}}return applyWorkingOps(rows,pendingWork())}
async function markWorkingAisle(warehouse,aisle){const op={action:'add',warehouse,aisle:Number(aisle),worker_id:workerId(),updated_at:new Date().toISOString(),op_id:'op-'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2))};queueWorkingOp(op);await syncPendingWork();const pending=pendingWork().some(x=>sameOp(x,op));return {ok:true,worker_id:op.worker_id,local:pending,error:pending?'Очікує повторної синхронізації':undefined}}
async function clearWorkingAisle(warehouse,aisle){const op={action:'remove',warehouse,aisle:Number(aisle),worker_id:workerId(),updated_at:new Date().toISOString(),op_id:'op-'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2))};queueWorkingOp(op);await syncPendingWork();const pending=pendingWork().some(x=>sameOp(x,op));return {ok:true,local:pending,error:pending?'Очікує повторної синхронізації':undefined}}
async function replaceAll(rows){if(!Array.isArray(rows))throw new Error('Nový seznam nemá správný formát');const clean=rows.map(x=>({warehouse:String(x.warehouse),aisle:Number(x.aisle),position:Number(x.position)}));if(clean.some(x=>!['DC2','DC3'].includes(x.warehouse)||!Number.isInteger(x.aisle)||!Number.isInteger(x.position)||x.aisle<1||x.position<1))throw new Error('Nový seznam obsahuje neplatné pozice');const inserted=await req('rpc/replace_qr_free_positions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({p_rows:clean})});const count=Array.isArray(inserted)?Number(inserted[0]):Number(inserted);if(!Number.isInteger(count)||count!==clean.length)throw new Error('Server zapsal '+(Number.isFinite(count)?count:'neznámý počet')+' pozic, očekáváno '+clean.length+'. Seznam nebyl potvrzen.');/* Výměna seznamu volných pozic nesmí mazat pracovní uličky ani čekající synchronizaci. */return clean.map(x=>({...x,occupied:false}))}
async function clearAll(){return replaceAll([])}
async function resetFromRaw(){const rows=[];for(const d of ['DC2','DC3'])for(const x of parse(window.QR_FREE_RAW[d]))rows.push({warehouse:d,aisle:x.aisle,position:x.position});return replaceAll(rows)}
async function hasList(){return (await allRows()).length>0}
window.QRPositionSync={init,refresh,allOccupied,markOccupied,resetFromRaw,replaceAll,clearAll,getWorkingAisles,markWorkingAisle,clearWorkingAisle,getWorkerId:workerId,hasList};
})();